# Generated by Django 4.2.7 on 2025-01-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_successful',
            field=models.IntegerField(blank=True, null=True, verbose_name='Успех миссии'),
        ),
    ]
