# Generated by Django 4.2.7 on 2024-11-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='description',
        ),
        migrations.AddField(
            model_name='flight',
            name='goal',
            field=models.TextField(blank=True, null=True, verbose_name='Цель'),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_successful',
            field=models.IntegerField(blank=True, null=True, verbose_name='Успех миссии'),
        ),
    ]
