# Generated by Django 4.2.7 on 2024-10-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronaut',
            name='specialization',
            field=models.CharField(blank=True),
        ),
    ]
