# Generated by Django 4.2.7 on 2024-10-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_astronaut_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronaut',
            name='country',
            field=models.CharField(blank=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='astronaut',
            name='specialization',
            field=models.CharField(blank=True, verbose_name='Специализация'),
        ),
    ]
