# Generated by Django 4.2.7 on 2024-10-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_astronaut_country_alter_astronaut_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='status',
            field=models.IntegerField(choices=[(1, 'Действует'), (2, 'Удален')], default=1, verbose_name='Статус'),
        ),
    ]
