# Generated by Django 4.2.7 on 2024-11-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_astronaut_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_successful',
            field=models.IntegerField(blank=True, null=True, verbose_name='Успех миссии'),
        ),
    ]
