# Generated by Django 4.2.7 on 2024-11-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_flight_is_successful'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='description',
        ),
        migrations.AddField(
            model_name='flight',
            name='goal',
            field=models.TextField(blank=True, null=True, verbose_name='Цель'),
        ),
    ]
