# Generated by Django 4.2.7 on 2024-11-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_flight_description_flight_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='astronautflight',
            name='value',
        ),
        migrations.AddField(
            model_name='astronautflight',
            name='captain',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
