# Generated by Django 4.2.7 on 2024-09-29 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 22, 3, 51, 25511, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
