# Generated by Django 4.2.7 on 2024-09-29 22:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0002_alter_flight_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='space_time',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 29, 22, 10, 57, 689434, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
