# Generated by Django 4.2.7 on 2024-10-01 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0003_alter_astronaut_space_time_alter_flight_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronautflight',
            name='value',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 1, 20, 51, 18, 96470, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
