# Generated by Django 4.2.7 on 2024-10-02 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0008_alter_flight_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 2, 12, 47, 49, 416238, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
